name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: [echo_message]
jobs:
  Task_A:
    runs-on: ubuntu-latest
    steps:      
      - name: Echo Message
        # commitメッセージにtask1を含む場合だけjobを実行する。それ以外のときは何もしない
        # 変数を${{}}で囲ってしまうと常にTrueが返されてしまうので注意
        if: "contains(github.event.client_payload.message, 'task1')"
        run: echo "${{github.event.client_payload.message}}"
  Task_B:
    runs-on: ubuntu-latest
    steps:      
      - name: Echo Message
        # commitメッセージにtask2を含む場合だけjobを実行する。それ以外のときは何もしない
        # 変数を${{}}で囲ってしまうと常にTrueが返されてしまうので注意
        if: "contains(github.event.client_payload.message, 'task2')"
        run: echo "${{github.event.client_payload.branch}}"
  Task_C:
    runs-on: ubuntu-latest
    steps:      
      - name: Echo Message
        # commitメッセージにtask3を含む場合だけjobを実行する。それ以外のときは何もしない
        # 変数を${{}}で囲ってしまうと常にTrueが返されてしまうので注意
        if: "contains(github.event.client_payload.message, 'task3')"
        run: echo "${{github.event.client_payload.commitid}}"
        
